kind: Pod
apiVersion: v1
metadata:
  name: alpine1
  labels:
    app: alpine
spec:
  containers:
  - name: alpine
    image: alpine
    command: ["sleep", "36000"]
  volumes:
  - name: named-volume-1
    configMap:
      name: non-existent-configmap
