apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: default
spec:
  selector:
    app: nginx
    type: lb
  ports:
    - protocol: TCP
      port: 80        # port exposed by the Service
      targetPort: 80  # port the container listens on
  type: NodePort
