apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentd-config
  namespace: kube-system
data:
  fluent.conf: |
    <source>
      @type tail
      @id in_tail_container_logs
      path /var/log/containers/*.log
      exclude_path ["/var/log/containers/fluentd-*_kube-system_*.log"]
      pos_file /var/log/fluentd-containers.log.pos
      tag kubernetes.*
      read_from_head true
      <parse>
        @type json
        time_key time
        time_type string
        time_format %Y-%m-%dT%H:%M:%S.%NZ
        keep_time_key false
      </parse>
    </source>

    # Adds Kubernetes metadata (pod name, namespace, labels, etc.) to each log record
    <filter kubernetes.**>
      @type kubernetes_metadata
      @id filter_kube_metadata
    </filter>

    <match kubernetes.**>
      @type opensearch
      @id out_opensearch
      host host.minikube.internal
      port 9200
      scheme http
      ssl_verify false
      logstash_format true
      logstash_prefix k8s-logs
      include_tag_key true

      <buffer>
        @type file
        path /var/log/fluentd-buffers/kubernetes.system.buffer
        flush_mode interval
        flush_interval 5s
        flush_thread_count 2
        retry_type exponential_backoff
        retry_forever true
        retry_max_interval 30
        chunk_limit_size 4M
        queue_limit_length 32
        overflow_action block
      </buffer>
    </match>